apiVersion: v1
kind: Service
metadata:
 name: voting-app
spec:
 selector:
    app: voting-app
    name: vote
 type: NodePort
 ports:
  - name: voting-app
    port: 80
    targetPort: 80
    nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
 name: result-app
spec:
 selector:
    app: voting-app
    name: result
 type: NodePort
 ports:
  - name: voting-app
    port: 80
    targetPort: 80
    nodePort: 30002

