apiVersion: apps/v1
kind: Deployment
metadata:
 name: redis
 labels:
    app: voting-app
    name: redis

spec:
 selector:
  matchLabels:
   app: voting-app
   name: redis
 replicas: 1
 template:
  metadata:
   labels:
    app: voting-app
    name: redis
  spec:
   containers:
   - name: redis
     image: redis:alpine

---
apiVersion: v1
kind: Service
metadata:
 name: redis
spec:
 ports:
 - name: redis
   port: 6379
   targetPort: 6379
 selector:
    app: voting-app
    name: redis

